### PR TITLE
Forced installation of latest npm, cached deps

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by fitzgen** [comment]
I'm no Travis CI wizard -- can you explain what these changes do?

**Comment by amilajack** [comment]
1. Cached node_modules for faster tests
2. Forced latest patch version of npm to prevent using buggy versions

**Comment by tivac** [comment]
Why is it doing a global install?

**Comment by amilajack** [comment]
@tivac npm needs to be globally installed.

**Comment by fitzgen** [comment]
Ok, thanks for the explanation!

**Pull request merged**
