### PR TITLE
Add option to skip mapping validation in generator

### PR DESCRIPTION
**Pull request by crisptrutski**
A performance boosting option for use in trusted contexts.

Extra context: #148

### CODE REVIEW

**Comment by fitzgen** [comment]
Can you add documentation to `README.md` describing this option, with a warning that using it is generally unsafe and should only be used if you really need to eek out the last bit of performance, and should probably never be passed in tests.

Will merge with that.

cc @mishoo, who wanted something like this some time ago.

**Comment by crisptrutski** [comment]
Great point about turning this off in tests, I'd have flubbed that.

**Comment by crisptrutski** [comment]
@fitzgen documented

**Comment by fitzgen** [comment]
Thanks!

**Pull request merged**
