### PR TITLE
fix the bug “TypeError: Cannot read property 'substr' of undefined”

### PR DESCRIPTION
**Pull request by jackytse**
fix the bug “TypeError: Cannot read property 'substr' of undefined”

### CODE REVIEW

**Comment by IgorMinar** [comment]
could this be merged please?

it fixes quite common issue #247 (also see driftyco/ionic-app-scripts#796 and angular/angular-cli#5476)

in the meantime, one can apply this patch to their project using:

```
(cd node_modules/source-map; curl https://patch-diff.githubusercontent.com/raw/mozilla/source-map/pull/257.patch | patch lib/source-node.js)
```

**Comment by jasonLaster** [comment]
@IgorMinar this looks good to me. Can you include a test that would have failed without the fix?

**Comment by KeitaElric** [comment]
Pls resolve confict and merge it.

**Comment by jruef** [comment]
Hi, could you please resolve the conflicts and merge. I really need this fix!

**Comment by erykpiast** [comment]
Please do!

**Comment by erykpiast** [comment]
Hey @fitzgen, I suppose you're in charge here, so I'll talk to you directly. Sorry for bothering you, but I hope it'll be more effective.

We have an emergency here. Notice that `source-map` isn't direct dependency for the most of people (I guess it's webpack's in many cases) and it's not so easy to just "use forked version until it's fixed properly". Currently I'm modifying my `node_modules` directory three levels deep after installation (even on CI; sounds quite fragile, doesn't it?) and I suppose it's the only way to push their code to production for many people right now.

I've spent quite a lot of time on debugging it to add a test and accelerate the work, without much success though. I did want to share what I've (not) found, but after writing screen-long comment on GitHub my browser crashed and I've lost everything. Shit happens. So the only thing I want to say: please consider to accept this quick, dirty, untested and "I don't really know why it works" fix, as it just resolves serious bug while not breaking any existing test, and try to find proper solution after that. People counts on you. Thank you in advance.

**Comment by fitzgen** [comment]
I don't maintain this repository anymore, that would be @tromey.

**Comment by lahdekorpi** [comment]
Any updates on this?

**Comment by natejgardner** [comment]
Please merge this! Without this fix, webpack is totally broken.

@tromey do you have an ETA?

**Comment by tromey** [comment]
I think this is interesting: https://github.com/mozilla/source-map/issues/247#issuecomment-320233757

**Comment by michal-filip** [comment]
We had the same issue when used as dependency of webpack-sources package. Resolution was to point to this PR explicitly in package.json to override the version webpack-sources uses. Thanks a lot for this!!
`"source-map": "https://github.com/mozilla/source-map/tarball/eb1a675a397cc4752358bec7e84e8e81d7798ac4"`

**Comment by tromey** [comment]
Going to merge this in #288 - same basic patch, just no merge conflict.

**Pull request closed without merging**
