### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by dineshks1** [comment]
Please review this merge.

**Comment by dineshks1** [comment]
@jasonLaster Waiting for your response for merge ppc64le code.

**Comment by ochameau** [comment]
Sorry for getting back to you so late. Previous maintainers of this repo switched to other jobs.

We started maintaining this code again and just moved to GitHub Actions in #464.
Please re-open if you would like to provide similar patch, but on github actions.

Otherwise, is there really a value in running in a distinct platform?
This code, hopefully, shouldn't have much platform specific failures.

**Pull request closed without merging**
