### PR TITLE
fixed global leakage of variable `value`

### PR DESCRIPTION
**Pull request by sokra**

### CODE REVIEW

**Comment by sokra** [comment]
Any reason why not using a test runner like mocha?

**Comment by fitzgen** [comment]
> Any reason why not using a test runner like mocha?

The tests need to run inside Firefox's internal test suite as well as on node, and at the time writing our own test runner was the easiest option.

**Comment by fitzgen** [comment]
Thanks

**Comment by sokra** [comment]
Could you please publish this?

**Comment by fitzgen** [comment]
Published.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
